// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrBZLMWdxDa6mhXMRfMWQwqwBJRkTKeoc',
    appId: '1:2762433205:web:f214f935e6543ed33ad4fc',
    messagingSenderId: '2762433205',
    projectId: 'ablony-a5db9',
    authDomain: 'ablony-a5db9.firebaseapp.com',
    storageBucket: 'ablony-a5db9.firebasestorage.app',
    measurementId: 'G-QEGNP6X4DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH6dy7zGcgvXUdALv6l8Km8GvndcDIcNA',
    appId: '1:2762433205:android:af2391c2d5d0b5ac3ad4fc',
    messagingSenderId: '2762433205',
    projectId: 'ablony-a5db9',
    storageBucket: 'ablony-a5db9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSjZiU1bUb9o7zV3ImGOXHRwY1yOtC7PI',
    appId: '1:2762433205:ios:df7f5dac495454143ad4fc',
    messagingSenderId: '2762433205',
    projectId: 'ablony-a5db9',
    storageBucket: 'ablony-a5db9.firebasestorage.app',
    androidClientId: '2762433205-4e87knanpqa0ikm0u9ns79vaa18pbghc.apps.googleusercontent.com',
    iosClientId: '2762433205-33dv8i71vtufo5i1bph165ika4upuepr.apps.googleusercontent.com',
    iosBundleId: 'com.ablony.app',
  );

}